import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'
import localFont from "next/font/local";

const atHaussAero = localFont({
  src: [
    {
      path: "../public/fonts/AtHaussAero-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/AtHaussAero-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/AtHaussAero-Semibold.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-athauss-aero", // CSS variable name
  display: "swap",
});

const nbArchitekt = localFont({
  src: [
    {
      path: "../public/fonts/NB_Architekt_Neue_Normal.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-nb-architekt",
  display: "swap",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{colorScheme: "dark"}} className={`dark ${atHaussAero.variable} ${nbArchitekt.variable}`}>  
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
